cpu_workers: 8

batch_size: 1000
stl_epochs: 20
mtl_epochs: 100

training_size_percentage: 75
test_size_percentage: 15
# Validation size is the rest of the percentage

nodes_before_split: 64
stl_learning_rate: 0.01
mtl_learning_rate: 0.01

hidden_layers: [64, 64]
# The activations list needs to be the length of hidden_layers + 1
# as the last layer is provided by nodes_before_split
activations: ['relu', 'relu', 'relu']
# weights or gradients
loss_converge_method: gradients

# data/cchvae_split.py
cchvae_locked_features_heloc: [1, 2, 4]
cchvae_locked_features_gmsc: [2, 10]
